name: widget_test_kit
description: "Declarative, readable widget-testing helpers for Flutter."
version: 0.2.0
homepage: https://github.com/KareemMuhammad/widget_test_kit
repository: https://github.com/KareemMuhammad/widget_test_kit
issue_tracker: https://github.com/KareemMuhammad/widget_test_kit/issues
topics:
  - testing
  - widget-testing
  - unit-testing
  - flutter

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
